trigger:
  branches:
    include:
    - main


pool:
  name: Default
  
steps:
- script: echo "Iniciando el pipeline..."
  displayName: 'Inicio'

- script: trunk build
  displayName: 'Construyendo el proyecto con Trunk'

- script: sudo npm install -g gh-pages
  displayName: 'Instalando gh-pages'

- script: gh-pages -d dist
  displayName: 'Desplegando en GitHub Pages'